-- Create page_views table
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  page_path text not null,
  city text,
  region text, -- holds province / state
  country text
);

-- Enable RLS on page_views table
alter table page_views enable row level security;

-- Policy: Anyone can insert view logs (unauthenticated public visitors)
create policy "Anyone can insert page views"
  on page_views for insert
  with check (true);

-- Policy: Only authenticated dashboard administrators can read view logs
create policy "Only authenticated users can view analytics"
  on page_views for select
  using (auth.role() = 'authenticated');
