-- Create contact_messages table
create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  status text default 'unread'::text not null
);

-- Enable RLS on contact_messages table
alter table contact_messages enable row level security;

-- Policy: Anyone can insert contact messages (public visitors)
create policy "Anyone can insert contact messages"
  on contact_messages for insert
  with check (true);

-- Policy: Only authenticated users (admins) can view or manage contact messages
create policy "Only authenticated users can view or manage contact messages"
  on contact_messages for all
  using (auth.role() = 'authenticated');
